version: '3'

services:
  cassandra:
    environment:
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
      - CASSANDRA_BROADCAST_ADDRESS=10.7.108.10
    ports:
      - "9042:9042"
    image: cassandra:3.11
    restart: always
  web:
    build: .
    command: python3 -m api
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
