version: '3'

services:
  cassandra:
    ports:
      - "9042:9042"
    image: cassandra:3.11
    restart: always
  web:
    build: .
    command: python3 -m api
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
